=head1 NAME

Jonk::Cookbook - recipes

=head1 RECIPES

L<Jonk::Cookbook::Basic> - basic usage.

L<Jonk::Cookbook::ForkModel> - with Parallel::Prefork.

L<Jonk::Cookbook::DequeueSpecificJob> - dequeue specific job.

L<Jonk::Cookbook::ErrorHandling> - error handling enqueue and dequeue.

L<Jonk::Cookbook::RetryJob> - retry job with wait few minitus.

=cut
