=head1 NAME

Jonk::Cookbook::Basic - basic usage for Jonk

=head1 USAGE

enqueue script:

    #! perl
    use strict;
    use warnings;
    use DBI;
    use Jonk::Client;
    
    my $dbh = DBI->connect('dbi:mysql:test','user','pass');
    my $jonk = Jonk::Client->new($dbh);
    my ( $sec, $min, $hour, $mday, $mon, $year, $wday, $yday, $isdst ) = localtime(time);
    my $time = sprintf('%04d-%02d-%02d %02d:%02d:%02d', $year + 1900, $mon + 1, $mday, $hour, $min, $sec);
    
    $jonk->enqueue('Your::Worker',{arg => 'job_data_here', time => $time});

worker script:

    #! perl
    use strict;
    use warnings;
    use DBI;
    use Jonk::Worker;
    use Your::Worker;
    
    my $dbh = DBI->connect('dbi:mysql:test','user','pass');
    my $jonk = Jonk::Worker->new($dbh => {functions => [qw/Your::Worker/]});
    
    while (1) {
        if (my $job = $jonk->dequeue) {
            my $worker = $job->{func}; # Your::Worker;
            $worker->work($job);
        } else {
            sleep(3); # wait for 3 sec.
        }
    }
    
=cut
